# VulnerabilityPatcher by CoolJWB.

# Patches: DeathPotions, DeathItems, CrashItems, Books, RougeEntity, Arrows, Riptide, FollowRange, DisconnectItems, EntityTag, Blocks, StructureBlocks, Chunks, ItemFrames.
# All patches added in the list below will be activated on server startup.
Patches:
  - DeathPotions
  - DeathItems
  - CrashItems
  - Books
  - RougeEntity
  - Arrows
  - Riptide
  - FollowRange
  - DisconnectItems
  - EntityTag
  - Blocks
  - StructureBlocks
  - Chunks
  - ItemFrames
  - Handswitch
  - Fireworks

# All entities added below will be blocked to use in a spawn egg.
BlockedEntityTags:
  - lightning_bolt
  - item_frame
  - falling_block
  - area_effect_cloud
  - phantom

Commands:
  Help:
    Permission: vulnerability.help
  Version:
    Permission: vulnerability.version
  Reload:
    Permission: vulnerability.reload
  Delete:
    Permission: vulnerability.delete
  BlockTags:
    Permission: vulnerability.tags.block
  UnblockTags:
    Permission: vulnerability.tags.unblock
  EnablePatch:
    Permission: vulnerability.patch.enable
  DisablePatch:
    Permission: vulnerability.patch.disable

Notify:
  Enabled: false
  Permission: vulnerability.notify

# Security Mode (EASY : MEDIUM : STRICT)
SecurityMode: "EASY"

# DevMode should be set to false, unless you're a developer of this plugin.
DevMode: false