name: VulnerabilityPatcher
version: 1.1
main: me.cooljwb.vulnerabilitypatcher.VulnerabilityPatcher
api-version: 1.14
authors: [CoolJWB]
description: Patches vurnelabilities that cause server instabilaty.
commands:
  vulnerabilitypatcher:
    aliases: [vp]
    description: The main command for VulnerabilityPatcher.
  getnbt:
    description: Reveals an items NBT data.