name: VulnerabilityPatcher
version: 0.5
main: me.cooljwb.vulnerabilitypatcher.VulnerabilityPatcher
api-version: 1.13
authors: [CoolJWB]
description: The brand new v0.4 VulnerabilityPatcher for 1.13.2 and 1.14 servers.
commands:
  vulnerabilitypatcher:
    aliases: [vp]
    description: The main command for VulnerabilityPatcher.
  getnbt:
    description: Reveals an items NBT data.