name: VulnerabilityPatcher
version: 0.1.1
main: me.cooljwb.vulnerabilitypatcher.VulnerabilityPatcher
api-version: 1.13
authors: [CoolJWB]
description: Patches the server vulnerabilities.
commands:
  vulnerabilitypatcher:
    aliases: [vp]
    description: The main command for VulnerabilityPatcher.
  getnbt:
    description: Reveals an items NBT data.