# VulnerabilityPatcher by CoolJWB
# Patches:
# DeathPotions, DeathItems, CrashSigns, Books, RougeEntity, Knockback, Riptide, FollowRange, DisconnectItems, CrashEgg.

Patches:
  - DeathPotions
  - DeathItems
  - CrashSigns
  - Books
  - RougeEntity
  - Knockback
  - Riptide
  - FollowRange
  - DisconnectItems
  - CrashEgg

Commands:
  Help:
    Permission: vulnerability.help
  Version:
    Permission: vulnerability.version
  Reload:
    Permission: vulnerability.reload

Notify:
  Enabled: false
  Permission: vulnerability.notify

# Should be set to false, unless you're a developer of this plugin.
DevMode: false