name: VulnerabilityPatcher
version: @version@
main: me.cooljwb.vulnerabilitypatcher.vulnerabilitypatcher.VulnerabilityPatcher
api-version: 1.13
authors: [CoolJWB]
description: Patches the server vulnerabilities.
commands:
  vulnerabilitypatcher:
    aliases: [vp]
    description: The main command for VulnerabilityPatcher.