# VulnerabilityPatcher by CoolJWB.

# Patches: DeathPotions, DeathItems, CrashItems, Books, RougeEntity, Knockback, Riptide, FollowRange, DisconnectItems, CrashEgg, EntityTag.
# All patches added in the list below will be activated on server startup.
Patches:
  - DeathPotions
  - DeathItems
  - CrashItems
  - Books
  - RougeEntity
  - Knockback
  - Riptide
  - FollowRange
  - DisconnectItems
  - CrashEgg
  - EntityTag

# All entities added below will be blocked to use in a spawn egg.
BlockedEntityTags:
  - lightning_bolt
  - falling_block

Commands:
  Help:
    Permission: vulnerability.help
  Version:
    Permission: vulnerability.version
  Reload:
    Permission: vulnerability.reload

Notify:
  Enabled: false
  Permission: vulnerability.notify

# DevMode should be set to false, unless you're a developer of this plugin.
DevMode: false

# This should not be changed unless you know what you're doing.
ConfVersion: 0